<?php

namespace Tests\Feature\Api\ContractCargo;

use App\Models\Contract;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class SplitCargoTest extends TestCase
{
    use RefreshDatabase;

    protected Model $contract;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->contract = Contract::factory()->create([
            'cargo_qty' => 400
        ]);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_splitting_cargo_returns_201()
    {
        $data = [
            'id' => $this->contract->id,
            'qty' => 100
        ];
        $response = $this->postJson('/api/cargo/split', $data);

        $response->assertStatus(201);
    }

    public function test_splitting_cargo_has_new_entry()
    {
        $data = [
            'id' => $this->contract->id,
            'qty' => 100
        ];
        $response = $this->postJson('/api/cargo/split', $data);

        $this->assertDatabaseHas('contracts', [
            'dep_airport_id' => $this->contract->dep_airport_id,
            'cargo_qty' => 100
        ]);
        $this->assertDatabaseCount('contracts', 2);
    }

    public function test_splitting_cargo_has_existing_with_remaining()
    {
        $data = [
            'id' => $this->contract->id,
            'qty' => 100
        ];
        $response = $this->postJson('/api/cargo/split', $data);

        $this->assertDatabaseHas('contracts', [
            'id' => $this->contract->id,
            'cargo_qty' => 300
        ]);
    }
}
