<?php

namespace Tests\Feature\Api\Contracts;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class BidForContractTest extends TestCase
{
    use RefreshDatabase;

    protected Model $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_contract_created_successfully()
    {
        $data = [
            'contract' => [
                'cargo' => 'Test',
                'cargo_type' => 1,
                'cargo_qty' => 4,
                'departure' => 'AYMR',
                'destination' => ['identifier' => 'AYMN'],
                'distance' => 30,
                'heading' => 25,
                'contract_value' => 250,
                'expires_at' => Carbon::now()->addDays(2),
            ],
            'userId' => $this->user->id
        ];
        $response = $this->postJson('/api/contracts/bid', $data);

        $response->assertStatus(201);
    }
}
